### ISSUE TITLE
High DPI support

### ISSUE THREAD

**Issue by upiter** [mrfearless/ModernUI#10]
# High DPI support is a must on modern systems

## Intro

ModernUI should support HiDPI and never use hardcoded values (like hardcoded button positions or font size) without rescaling.

Example:
![muiprogressdots-hidpi-001](https://user-images.githubusercontent.com/795353/46047068-251a4300-c12c-11e8-8512-8ac445529151.png)

## Links

- [High DPI Desktop Application Development on Windows](https://docs.microsoft.com/en-us/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows)
- [High DPI Reference](https://docs.microsoft.com/en-us/windows/desktop/hidpi/high-dpi-reference)
- [WM_DPICHANGED](https://docs.microsoft.com/en-us/windows/desktop/hidpi/wm-dpichanged) message (code samples)

## To do

- Implement HiDPI support in all ModernUI controls and examples
- Take care of Per-Monitor (V2) DPI Awareness

**Comment by mrfearless** [comment]
Thanks.

Yes its something that I have been thinking about for a while now - its on my long todo list :D

My main development PC is Windows 7 x64 so some of the dpi aware functions are only supported on higher versions - although there is still lots I can do at the lower level for each control in regard to positions and calculating widths/heights etc based on current dpi settings. Some of that stuff I will have to dive into and learn a bit more about.

I don't have a time frame for implementing this unfortunately. 

I appreciate you taking the time to try out the ModernUI libraries/controls and for your feedback. Thanks again.

**Comment by upiter** [comment]
> I don't have a time frame for implementing this unfortunately.

In this case it's better to mention in documentation about ModernUI DPI Awareness and to provide recommendations to use **predefined dialogs** instead of dynamic creation if one needs smooth transition to modern OS with High DPI.

**Comment by mrfearless** [comment]
Closing as this is not a priority at this time.

**Comment by upiter** [comment]
Caption bar is big, but text in caption is small, buttons are small, see screen.
Screen of MUIText example:
<img width="1361" alt="muitext_caption_bar" src="https://user-images.githubusercontent.com/795353/48036790-e3dd7000-e17a-11e8-8c76-cdf87d44cdf6.png">
