### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by upiter** [mrfearless/ModernUI#11]
# Create installation script to install all ModernUI libraries and includes

## Intro

Each time I update ModernUI library, I need to copy bunch of files to `include` and `lib` folder.
With installation script this process would be much more comfortable.

## Solution

- Create `install.cmd` for Windows
- Create `install.sh` for macOS and Linux

**Comment by mrfearless** [comment]
Ive added a windows `install.cmd` batch file for anyone who downloads the entire github repo and runs `install.cmd` from the root of the repo. It assumes the default `\masm32\` folder is on the current drive, however it can be passed a parameter to specify the installation folder if required.

And also created a `ModernUI_AllControls.zip` package in the release folder with just the lib and include files with its own `install.cmd` (extract to a folder, run that `install.cmd` to copy to a default `\masm32\` folder or a specified folder)

Don't know macOS and Linux scripting enough to provide an install file - so looking for help on that if anyone wants to contribute. Thanks in advance.

**Comment by mrfearless** [comment]
The windows install.cmd was created, but no additional pull request or suggestions for macOS or Linux scripting, so will close this for the moment, as windows is the main targeted OS for development and use.
