### ISSUE TITLE
MUICaptionBar mouse move [Wine]

### ISSUE THREAD

**Issue by upiter** [mrfearless/ModernUI#7]
_Notice_: This issue is about running ModernUI on [Wine](https://www.winehq.org/)

# MUICaptionBar mouse move Report

## Description
Mouse pointer can't access caption bar. Cursor becomes sticky to bottom of caption bar and window is moving with cursor when you try to access caption bar.

## Workaround
Press Esc, then cursor is released for a while and you could click close button inside caption bar.

## Where to check sources (just guess)
 **_MUI_CaptionBarWndProc** in [ModernUI_CaptionBar.Asm](https://github.com/mrfearless/ModernUI/blob/master/Controls/ModernUI_CaptionBar/ModernUI_CaptionBar.asm):
  - WM_NCHITTEST
  - WM_MOUSEMOVE

**Comment by mrfearless** [comment]
Thanks for letting me know about that. Thats cool you are using it under wine :D

I did some googling to see that there might have been issues with WM_NCHITTEST under wine using WindowFromPos and the like - cant say exactly why that is. 

I added an additional check to see if the control has reported the mouse button is down, if it is not then we dont do anything - which hopefully will prevent the sticky caption window move issue.

**Comment by mrfearless** [comment]
Hi @upiter, just wanted to check with you did this change help at all, or is the same issue occurring?

**Comment by mrfearless** [comment]
Haven't heard from you since, I will assume it is fixed for now. You can always re-open if its still persisting.

**Comment by upiter** [comment]
I can't confirm that it's fixed. I have same issues with latest MUIText from Examples.
