### ISSUE TITLE
Error checks are missing in MUITextCreate

### ISSUE THREAD

**Issue by upiter** [mrfearless/ModernUI#8]
# Error checks are missing in MUITextCreate

## Intro
`MUITextCreate` must always check result of system functions like `CreateFont`.
Currently `MUITextCreate` never checks result of `CreateFont` and assumes success even in case of error (in case of missing font, for example).

## How to reproduce
- Call `MUI TextCreate` with random font name
- No error checks will be performed in `MUITextCreate`
- Invalid font handle will be saved via `_MUI_TextSetFontTableHandle`
- Invalid font handle will be used in `_MUI_TextPaintText`

## Result
- All characters are displayed as squares

## Workaround
- Comment (disable) all `MUITextCreate` function calls
**or**
- Call `CreateFont` before `MUITextCreate` to be sure that specific font is installed

## Affected functions

Public:

- MUITextCreate
- MUITextSetProperty
- MUITextGetProperty

Internal:

in _ModernUI_Text/ModernUI_Text.asm_

- `_MUI_TextSetFontFamilySize` - source of problem, CreateFont's return value never checked
- `_MUI_TextSetFontTableHandle` - could save invalid handle, called by _MUI_TextSetFontFamilySize
- `_MUI_TextGetFontTableHandle` - may return invalid handle previously saved by _MUI_TextSetFontTableHandle
- `_MUI_TextPaintText` - doesn't check result of MUIGetExtProperty, could use invalid handle

## Code sample

**_MUI_TextSetFontFamilySize**:
```asm
;--------------------------------
; Create font
;--------------------------------
Invoke _MUI_TextGetFontTableHandle, hWin, dwStyle
mov hFont, eax
.IF eax == 0 ; no handle found in fonttable
    ;PrintText 'New Font'
    Invoke CreateFont, dwFontHeight, 0,0,0, dwFontWeight, bFontItalic, bFontUnderline,0,0,0,0, PROOF_QUALITY, FF_DONTCARE, MUITextFont
   ; BUG: missing CreateFont error checks
    mov hFont, eax
    ; save handle to fonttable
    Invoke _MUI_TextSetFontTableHandle, hWin, dwStyle, hFont
.ELSE ; use handle from fonttable instead
.ENDIF
Invoke MUISetExtProperty, hWin, @TextFont, hFont
```
By default szMUITextFontSegoe ("Segoe UI") is used, but this font could be missing on particular system, as well as any other font:

```asm
mov eax, dwFontFamily
.IF eax == MUITS_FONT_SEGOE
    lea eax, szMUITextFontSegoe
.ELSEIF eax == MUITS_FONT_TAHOMA
    lea eax, szMUITextFontTahoma
.ELSEIF eax == MUITS_FONT_ARIAL
    lea eax, szMUITextFontArial
.ELSEIF eax == MUITS_FONT_TIMES
    lea eax, szMUITextFontTimes
.ELSEIF eax == MUITS_FONT_COURIER
    lea eax, szMUITextFontCourier
.ELSEIF eax == MUITS_FONT_VERDANA
    lea eax, szMUITextFontVerdana
.ELSE
    ; BUG: Are you so sure about presence of this font on particular system?
    lea eax, szMUITextFontSegoe
.ENDIF
mov MUITextFont, eax
```

**_MUI_TextPaintText**:

```asm
Invoke MUIGetExtProperty, hWin, @TextFont
mov hFont, eax

; BUG: no checks performed

Invoke SelectObject, hdc, hFont
mov hOldFont, eax
```

## To do

- Check all functions for 'happy no errors' behaviour
- Add error checks after calling system functions
- Add error checks after calling internal functions
- Stop assuming that all systems (in future or in past) have any requested font installed

**Comment by mrfearless** [comment]
Thanks for letting me know about this. 

I think that I will add a check just after CreateFont and before saving the handle to the font table. If font doesnt exist, I will look to use the lfMessageFont logfont (retrieved via `Invoke SystemParametersInfo, SPI_GETNONCLIENTMETRICS, SIZEOF NONCLIENTMETRICS, Addr ncm, 0`) as a fallback - and set the height, weight, italic, underline before calling `CreateFontIndirect`

Additionally I will add a function to check if WM_SETFONT or MUITextSetProperty @TextFont is actually a font, and allow it to be set if it is - may have to also use the lfMessageFont as a fallback if the font doesnt exists, so there is at least a default font that control can use

**Comment by mrfearless** [comment]
Ive updated ModernUI_Text control to use the lfMessageFont logfont as mentioned above as a fallback and added in a check for WM_SETFONT and MUITextSetProperty if @TextFont is actually a font

**Comment by mrfearless** [comment]
Has been implemented. Can always be re-opened if needed.

**Comment by upiter** [comment]
Seems to be fixed (MUIText example as test).
